/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import controller.Conexao;
import java.awt.Image;
import java.awt.Toolkit;
import java.net.URL;
import java.util.Scanner;
import java.util.ArrayList;

/**
 *
 * @author yuril
 */
public class FormHera extends javax.swing.JFrame {

    private String portaEscolhida;

    ArrayList<String> nomesPortas = new ArrayList();

    Conexao conn = new Conexao();
    //Arduino model = new Arduino();

    /**
     * Creates new form FormCasaHera
     */
    public FormHera() {
        initComponents();
        setIcon();
        this.setResizable(false);
        jTextFieldSP.setEnabled(false);
        jButtonEnviarSP.setEnabled(false);

        //MODO MANUAL INICIA COMO PADRÃO//
        //Esquerda da tela
        jButtonManual.setEnabled(false);
        jButtonAutomatico.setEnabled(false);
        jLabel1.setEnabled(false);//Temperatura
        jLabel3.setEnabled(false);//FAN
        jLabel7.setEnabled(false);//Modos de Operação
        jLabel6.setEnabled(false);//Velocidade do FAN
        jLabelPercentFAN.setEnabled(false);
        jLabelTempInterna.setEnabled(false);//Temperatura
        jLabelFan.setEnabled(false);//FAN
        jButtonEnviarManual.setEnabled(false);//Botão
        jSliderVelocidadeFAN.setEnabled(false);//Botão
        //Direita da tela
        jLabel8.setEnabled(false);//Modo Automático
        jLabel2.setEnabled(false);//SP
        jLabel5.setEnabled(false);//PID
        jLabel4.setEnabled(false);//Mudar SP
        jLabelSP.setEnabled(false);//SP
        jLabelPID.setEnabled(false);//PID
        jTextFieldSP.setEnabled(false);//SP
        jButtonEnviarSP.setEnabled(false);//Botão

        jLabelSP.setText("");
        jLabelPID.setText("");

        conn.descobrirPortas();

        for (int i = 0; i < conn.sizePortas(); i++) {
            jComboBoxPortasSeriais.addItem(conn.nomesPortas(i));
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabelSP = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jTextFieldSP = new javax.swing.JTextField();
        jButtonEnviarSP = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabelPID = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jSliderVelocidadeFAN = new javax.swing.JSlider();
        jButtonEnviarManual = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jButtonManual = new javax.swing.JButton();
        jButtonAutomatico = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jLabelPercentFAN = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jComboBoxPortasSeriais = new javax.swing.JComboBox<>();
        jButtonConectar = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jLabelTempInterna = new javax.swing.JLabel();
        jLabelFan = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Surpervisório");

        jPanel1.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));

        jLabelSP.setBackground(new java.awt.Color(255, 0, 51));
        jLabelSP.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabelSP.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelSP.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel2.setText("Set Point");

        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Mudar SP");

        jTextFieldSP.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jTextFieldSP.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        jButtonEnviarSP.setText("Enviar");
        jButtonEnviarSP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEnviarSPActionPerformed(evt);
            }
        });

        jLabel5.setText("PID");

        jLabelPID.setBackground(new java.awt.Color(255, 0, 51));
        jLabelPID.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabelPID.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelPID.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel8.setText("Modo Automático:");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel8)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addGap(11, 11, 11)
                                .addComponent(jLabel2))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jTextFieldSP)
                                .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabelSP, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelPID, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(28, 28, 28)
                                .addComponent(jLabel5))
                            .addComponent(jButtonEnviarSP))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabelSP, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabelPID, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldSP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonEnviarSP))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));

        jSliderVelocidadeFAN.setValue(0);
        jSliderVelocidadeFAN.setEnabled(false);
        jSliderVelocidadeFAN.setVerifyInputWhenFocusTarget(false);
        jSliderVelocidadeFAN.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jSliderVelocidadeFANStateChanged(evt);
            }
        });

        jButtonEnviarManual.setText("Enviar");
        jButtonEnviarManual.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEnviarManualActionPerformed(evt);
            }
        });

        jLabel6.setText("Velocidade FAN:");

        jButtonManual.setText("Manual");
        jButtonManual.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonManualActionPerformed(evt);
            }
        });

        jButtonAutomatico.setText("Automático");
        jButtonAutomatico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAutomaticoActionPerformed(evt);
            }
        });

        jLabel7.setText("Modos de Operação:");

        jLabelPercentFAN.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelPercentFAN.setText("Desligado");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jButtonManual)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButtonAutomatico))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGap(0, 15, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButtonEnviarManual, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jSliderVelocidadeFAN, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabelPercentFAN, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonManual)
                    .addComponent(jButtonAutomatico))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jLabelPercentFAN, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(7, 7, 7)
                .addComponent(jSliderVelocidadeFAN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addComponent(jButtonEnviarManual)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jButtonConectar.setText("Conectar");
        jButtonConectar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonConectarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jComboBoxPortasSeriais, 0, 274, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(jButtonConectar, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBoxPortasSeriais, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonConectar))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel4.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));

        jLabelTempInterna.setBackground(new java.awt.Color(255, 0, 51));
        jLabelTempInterna.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabelTempInterna.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelTempInterna.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabelFan.setBackground(new java.awt.Color(255, 0, 51));
        jLabelFan.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabelFan.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelFan.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel1.setText("Temperatura");

        jLabel3.setText("FAN");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabelTempInterna, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(17, 17, 17)
                        .addComponent(jLabelFan, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addComponent(jLabel1)
                        .addGap(57, 57, 57)
                        .addComponent(jLabel3)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabelTempInterna, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabelFan, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(8, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(8, 8, 8)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(8, Short.MAX_VALUE))
        );

        setSize(new java.awt.Dimension(448, 374));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonConectarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonConectarActionPerformed
        if (jButtonConectar.getText().equals("Conectar")) {
            if (conn.conectar(conn.portas(jComboBoxPortasSeriais.getSelectedIndex()))) {
                portaEscolhida = conn.portas(jComboBoxPortasSeriais.getSelectedIndex());
                jButtonConectar.setText("Desconectar");
                jComboBoxPortasSeriais.setEnabled(false);

                conn.enviar("m", String.valueOf(jSliderVelocidadeFAN.getValue()));
                //Esquerda da tela
                jButtonManual.setEnabled(false);
                jButtonAutomatico.setEnabled(true);
                jLabel1.setEnabled(true);//Temperatura
                jLabel3.setEnabled(true);//FAN
                jLabel7.setEnabled(true);//Modos de Operação
                jLabel6.setEnabled(true);//Velocidade do FAN
                jLabelPercentFAN.setEnabled(true);
                jLabelTempInterna.setEnabled(true);//Temperatura
                jLabelFan.setEnabled(true);//FAN
                jButtonEnviarManual.setEnabled(true);//Botão
                jSliderVelocidadeFAN.setEnabled(true);//Botão
                //Direita da tela
                jLabel8.setEnabled(false);//Modo Automático
                jLabel2.setEnabled(false);//SP
                jLabel5.setEnabled(false);//PID
                jLabel4.setEnabled(false);//Mudar SP
                jLabelSP.setEnabled(false);//SP
                jLabelPID.setEnabled(false);//PID
                jTextFieldSP.setEnabled(false);//SP
                jButtonEnviarSP.setEnabled(false);//Botão
                jLabelSP.setText("");
                jLabelPID.setText("");
            }

            // create a new thread that listens for incoming text and populates the graph
            Thread thread = new Thread() {
                @Override
                public void run() {
                    Scanner scanner = new Scanner(conn.receber());
                    while (scanner.hasNextLine()) {
                        try {
                            String line = scanner.nextLine();
                            if (line.startsWith("t")) {
                                line = line.replace("t", "");
                                float number = Float.parseFloat(line);
                                jLabelTempInterna.setText(String.format("%.2f" + "ºC", number));
                            } else if (line.startsWith("s")) {
                                line = line.replace("s", "");
                                float number = Float.parseFloat(line);
                                jLabelSP.setText(String.format("%.2f" + "ºC", number));
                            } else if (line.startsWith("f")) {
                                line = line.replace("f", "");
                                float number = Float.parseFloat(line);
                                jLabelFan.setText(String.format("%.0f" + "%%", number));
                            } else if (line.startsWith("PID = ")) {
                                line = line.replace("PID = ", "");
                                float number = Float.parseFloat(line);
                                jLabelPID.setText(String.format("%.0f", number));
                            }

                        } catch (Exception e) {
                        }
                    }
                    scanner.close();
                }
            };
            thread.start();
        } else {
            // disconnect from the serial port
            conn.desconectar();
            jComboBoxPortasSeriais.setEnabled(true);
            jLabelTempInterna.setText("");
            jLabelSP.setText("");
            jLabelFan.setText("");
            jTextFieldSP.setEnabled(false);
            jButtonEnviarSP.setEnabled(false);
            jButtonConectar.setText("Conectar");

            jButtonManual.setEnabled(false);
            jButtonAutomatico.setEnabled(false);
            jLabel6.setEnabled(true);
            jSliderVelocidadeFAN.setEnabled(true);
            jButtonEnviarManual.setEnabled(true);
            jLabel8.setEnabled(false);
            jLabel2.setEnabled(false);
            jLabel5.setEnabled(false);
            jLabel4.setEnabled(false);
            jLabel1.setEnabled(false);
            jLabel3.setEnabled(false);
            jLabel7.setEnabled(false);
            jLabel6.setEnabled(false);
            jLabelPercentFAN.setEnabled(false);
            jLabelSP.setEnabled(false);
            jLabelPID.setEnabled(false);
            jLabelTempInterna.setEnabled(false);
            jLabelFan.setEnabled(false);
            jButtonEnviarManual.setEnabled(false);
            jSliderVelocidadeFAN.setEnabled(false);
            jSliderVelocidadeFAN.setValue(0);
        }
    }//GEN-LAST:event_jButtonConectarActionPerformed

    private void jButtonEnviarSPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEnviarSPActionPerformed
        conn.enviar("s", jTextFieldSP.getText());

        jTextFieldSP.setText("");
    }//GEN-LAST:event_jButtonEnviarSPActionPerformed

    private void jButtonManualActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonManualActionPerformed
        conn.enviar("m", String.valueOf(jSliderVelocidadeFAN.getValue()));

        //Esquerda da tela
        jButtonManual.setEnabled(false);
        jButtonAutomatico.setEnabled(true);
        jLabel1.setEnabled(true);//Temperatura
        jLabel3.setEnabled(true);//FAN
        jLabel7.setEnabled(true);//Modos de Operação
        jLabel6.setEnabled(true);//Velocidade do FAN
        jLabelPercentFAN.setEnabled(true);
        jLabelTempInterna.setEnabled(true);//Temperatura
        jLabelFan.setEnabled(true);//FAN
        jButtonEnviarManual.setEnabled(true);//Botão
        jSliderVelocidadeFAN.setEnabled(true);//Botão
        //Direita da tela
        jLabel8.setEnabled(false);//Modo Automático
        jLabel2.setEnabled(false);//SP
        jLabel5.setEnabled(false);//PID
        jLabel4.setEnabled(false);//Mudar SP
        jLabelSP.setEnabled(false);//SP
        jLabelPID.setEnabled(false);//PID
        jTextFieldSP.setEnabled(false);//SP
        jButtonEnviarSP.setEnabled(false);//Botão

        jLabelSP.setText("");
        jLabelPID.setText("");
    }//GEN-LAST:event_jButtonManualActionPerformed

    private void jButtonAutomaticoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAutomaticoActionPerformed
        conn.enviar("a", jTextFieldSP.getText());

        //Esquerda da tela
        jButtonManual.setEnabled(true);
        jButtonAutomatico.setEnabled(false);
        jLabel1.setEnabled(true);//Temperatura
        jLabel3.setEnabled(true);//FAN
        jLabel7.setEnabled(false);//Modos de Operação
        jLabel6.setEnabled(false);//Velocidade do FAN
        jLabelPercentFAN.setEnabled(false);
        jLabelTempInterna.setEnabled(true);//Temperatura
        jLabelFan.setEnabled(true);//FAN
        jButtonEnviarManual.setEnabled(false);//Botão
        jSliderVelocidadeFAN.setEnabled(false);//Botão
        //Direita da tela
        jLabel8.setEnabled(true);//Modo Automático
        jLabel2.setEnabled(true);//SP
        jLabel5.setEnabled(true);//PID
        jLabel4.setEnabled(true);//Mudar SP
        jLabelSP.setEnabled(true);//SP
        jLabelPID.setEnabled(true);//PID
        jTextFieldSP.setEnabled(true);//SP
        jButtonEnviarSP.setEnabled(true);//Botão
    }//GEN-LAST:event_jButtonAutomaticoActionPerformed

    private void jButtonEnviarManualActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEnviarManualActionPerformed
        conn.enviar("m", String.valueOf(jSliderVelocidadeFAN.getValue()));
    }//GEN-LAST:event_jButtonEnviarManualActionPerformed

    private void jSliderVelocidadeFANStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jSliderVelocidadeFANStateChanged
        if (jSliderVelocidadeFAN.getValue() == 0) {
            jSliderVelocidadeFAN.setToolTipText("Desligado");
            jLabelPercentFAN.setText("Desligado");
        } else if (jSliderVelocidadeFAN.getValue() == 100) {
            jSliderVelocidadeFAN.setToolTipText("Máximo");
            jLabelPercentFAN.setText("Máximo");
        } else {
            jSliderVelocidadeFAN.setToolTipText(String.valueOf(jSliderVelocidadeFAN.getValue()));
            jLabelPercentFAN.setText(String.valueOf(jSliderVelocidadeFAN.getValue()) + "%");
        }
    }//GEN-LAST:event_jSliderVelocidadeFANStateChanged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormHera.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormHera.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormHera.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormHera.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormHera().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAutomatico;
    private javax.swing.JButton jButtonConectar;
    private javax.swing.JButton jButtonEnviarManual;
    private javax.swing.JButton jButtonEnviarSP;
    private javax.swing.JButton jButtonManual;
    private javax.swing.JComboBox<String> jComboBoxPortasSeriais;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabelFan;
    private javax.swing.JLabel jLabelPID;
    private javax.swing.JLabel jLabelPercentFAN;
    private javax.swing.JLabel jLabelSP;
    private javax.swing.JLabel jLabelTempInterna;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JSlider jSliderVelocidadeFAN;
    private javax.swing.JTextField jTextFieldSP;
    // End of variables declaration//GEN-END:variables

    private void setIcon() {
        URL caminhoIcone = getClass().getResource("/imagens/Hera.png");
        Image iconePrograma = Toolkit.getDefaultToolkit().getImage(caminhoIcone);
        this.setIconImage(iconePrograma);
    }
}
